import { defineRecipe } from "@chakra-ui/react";

// Canonical interaction contract: hover-in uses `enter` duration + ease-out;
// press feedback is `instant` via transform scale; focus keeps the global ring.
export const khulwaButtonRecipe = defineRecipe({
  className: "khulwa-button",
  base: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    appearance: "none",
    border: "0",
    cursor: "pointer",
    fontFamily: "body",
    fontWeight: "medium",
    whiteSpace: "nowrap",
    userSelect: "none",
    flexShrink: "0",
    transitionProperty: "background-color, border-color, color, transform, box-shadow, opacity",
    transitionDuration: "enter",
    transitionTimingFunction: "enter",
    _active: { transform: "scale(0.97)", transitionDuration: "instant" },
    _motionReduce: { _active: { transform: "none" } },
    _disabled: { opacity: 0.5, cursor: "not-allowed" },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "border.focus",
      outlineOffset: "2px",
    },
  },
  variants: {
    visual: {
      solid: {
        bg: "fg.default",
        color: "fg.inverse",
        _hover: { bg: "fg.muted" },
        _active: { bg: "fg.muted", transform: "scale(0.97)" },
      },
      tonal: {
        bg: "primary.subtle",
        color: "primary.pressed",
        _hover: { bg: "primary.default", color: "primary.fg" },
        _active: { bg: "primary.pressed", color: "primary.fg" },
      },
      accent: {
        bg: "accent.default",
        color: "accent.fg",
        _hover: { bg: "accent.hover" },
        _active: { bg: "accent.pressed", transform: "scale(0.97)" },
      },
      ink: {
        bg: "fg.default",
        color: "fg.inverse",
        _hover: { bg: "fg.muted" },
        _active: { bg: "fg.muted" },
      },
      outline: {
        bg: "transparent",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "border.default",
        color: "fg.default",
        _hover: { bg: "surface.muted", borderColor: "border.emphasized" },
        _active: { bg: "bg.emphasized", borderColor: "border.strong" },
      },
      ghost: {
        bg: "transparent",
        color: "fg.muted",
        _hover: { bg: "surface.muted", color: "fg.default" },
        _active: { bg: "bg.emphasized" },
      },
      chip: {
        bg: "bg.elevated",
        color: "fg.muted",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "border.default",
        boxShadow: "sm",
        _hover: { bg: "bg.emphasized", color: "fg.default", borderColor: "border.strong" },
        _active: { bg: "bg.emphasized", transform: "scale(0.96)" },
      },
      danger: {
        bg: "transparent",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "status.danger",
        color: "status.danger",
        _hover: { bg: "status.danger", color: "fg.inverse" },
        _active: { bg: "status.danger", color: "fg.inverse", transform: "scale(0.97)" },
      },
    },
    size: {
      sm: { h: "8", minW: "8", paddingInline: "3", fontSize: "sm" },
      md: { h: "10", minW: "10", paddingInline: "4", fontSize: "sm" },
      lg: { h: "12", minW: "12", paddingInline: "6", fontSize: "md" },
      xl: { h: "16", minW: "16", paddingInline: "8", fontSize: "lg" },
    },
    shape: {
      pill: { rounded: "pill" },
      rounded: { rounded: "controlWide" },
      circle: { rounded: "circle", aspectRatio: "1", paddingInline: "0" },
    },
  },
  defaultVariants: {
    visual: "solid",
    size: "md",
    shape: "rounded",
  },
});
