"use client";

import { useTranslations } from "next-intl";
import type { ReactNode } from "react";
import { useProgress } from "@/services/progress";
import { formatDuration } from "../utils";
import { WeeklyBars } from "./weekly-bars";

function MetricCard({ title, value, children }: { title: string; value?: string; children: ReactNode }) { return <section className="rounded-panel border border-sage-300 bg-base-100 p-5 sm:p-6"><header className="flex items-baseline justify-between gap-4"><h2 className="font-semibold text-sage-1000">{title}</h2>{value ? <span className="text-sm tabular-nums text-sage-700">{value}</span> : null}</header><div className="mt-6">{children}</div></section>; }
export function ProgressPage() { const t = useTranslations("khulwa.progress"); const { data: day } = useProgress("day"); const { data: week, isPending } = useProgress("week"); const todayTotal = day?.totalSeconds ?? 0; const series = week?.series ?? []; const weekTotal = week?.totalSeconds ?? 0; const isEmpty = !isPending && weekTotal === 0 && todayTotal === 0; return <main className="min-h-dvh overflow-y-auto bg-base-200 px-5 pb-28 pt-24 sm:px-8"><div className="mx-auto grid max-w-5xl gap-6"><header><h1 className="text-3xl font-semibold tracking-normal text-sage-1000 sm:text-4xl">{t("title")}</h1><p className="mt-2 text-sm text-sage-700">{t("subtitle")}</p></header>{isEmpty ? <section className="rounded-panel border border-dashed border-sage-300 bg-base-100 p-12 text-center text-sm text-sage-700">{t("empty")}</section> : <div className="grid gap-5 md:grid-cols-2"><MetricCard title={t("today")} value={formatDuration(todayTotal)}><div className="grid min-h-48 place-items-center rounded-panel border border-sage-300 bg-sage-100 p-6 text-center"><span className="khulwa-numeric text-5xl font-bold tabular-nums text-sage-1000">{formatDuration(todayTotal)}</span><span className="mt-2 text-sm text-sage-700">{t("today")}</span></div></MetricCard><MetricCard title={t("last7Days")} value={formatDuration(weekTotal)}><WeeklyBars series={series} /></MetricCard></div>}</div></main>; }
