"use client";

import { useTranslations } from "next-intl";
import type { ReactNode } from "react";
import { useProgress } from "@/services/progress";
import { CATEGORIES, formatDuration, type CategoryId } from "../categories";
import { CategoryBar } from "./category-bar";
import { CategoryDonut } from "./category-donut";
import { WeeklyBars } from "./weekly-bars";

const EMPTY: Partial<Record<CategoryId, number>> = {};
function sumTotals(totals: Partial<Record<CategoryId, number>>): number { return CATEGORIES.reduce((sum, category) => sum + (totals[category.id] ?? 0), 0); }
function MetricCard({ title, value, children }: { title: string; value?: string; children: ReactNode }) { return <section className="rounded-panel border border-sage-300 bg-base-100 p-5 sm:p-6"><header className="flex items-baseline justify-between gap-4"><h2 className="font-semibold text-sage-1000">{title}</h2>{value ? <span className="text-sm tabular-nums text-sage-700">{value}</span> : null}</header><div className="mt-6">{children}</div></section>; }
export function ProgressPage() { const t = useTranslations("khulwa.progress"); const tCat = useTranslations("khulwa.categories"); const { data: day } = useProgress("day"); const { data: week, isPending } = useProgress("week"); const today = day?.totals ?? EMPTY; const todayTotal = sumTotals(today); const series = week?.series ?? []; const weekTotal = sumTotals(week?.totals ?? EMPTY); const max = Math.max(...CATEGORIES.map((category) => today[category.id] ?? 0), 1); const isEmpty = !isPending && weekTotal === 0 && todayTotal === 0; return <main className="min-h-dvh overflow-y-auto bg-base-200 px-5 pb-28 pt-24 sm:px-8"><div className="mx-auto grid max-w-5xl gap-6"><header><h1 className="text-3xl font-semibold tracking-normal text-sage-1000 sm:text-4xl">{t("title")}</h1><p className="mt-2 text-sm text-sage-700">{t("subtitle")}</p></header>{isEmpty ? <section className="rounded-panel border border-dashed border-sage-300 bg-base-100 p-12 text-center text-sm text-sage-700">{t("empty")}</section> : <div className="grid gap-5 md:grid-cols-2"><MetricCard title={t("today")} value={formatDuration(todayTotal)}><div className="grid place-items-center gap-6"><CategoryDonut totals={today}><span className="text-lg font-semibold tabular-nums text-sage-1000">{formatDuration(todayTotal)}</span><span className="text-xs text-sage-700">{t("today")}</span></CategoryDonut><div className="grid w-full gap-4">{CATEGORIES.map((category) => <CategoryBar color={category.color} id={category.id} key={category.id} max={max} seconds={today[category.id] ?? 0} />)}</div></div></MetricCard><MetricCard title={t("last7Days")} value={formatDuration(weekTotal)}><WeeklyBars series={series} /><div className="mt-5 flex flex-wrap justify-center gap-x-4 gap-y-2">{CATEGORIES.map((category) => <span className="flex items-center gap-1.5 text-xs text-sage-700" key={category.id}><span className="size-2.5 rounded-full" style={{ backgroundColor: category.color }} />{tCat(category.id)}</span>)}</div></MetricCard></div>}</div></main>; }
