"use client";

import { useEffect, useRef, useState } from "react";
import { Command } from "cmdk";
import { useTranslations } from "next-intl";
import { useHotkey } from "@/modules/shortcuts";
import { useUiPrefsStore } from "@/modules/ui-prefs";
import { CMD_PALETTE_HINT_ID } from "../constants";
import { useCommands } from "../commands";

export function CommandPalette() { const t = useTranslations("palette"); const [open, setOpen] = useState(false); const groups = useCommands(); const dismissHint = useUiPrefsStore((state) => state.dismissHint); const restoreRef = useRef<HTMLElement | null>(null); const contentRef = useRef<HTMLDivElement>(null); const openPalette = () => { restoreRef.current = document.activeElement as HTMLElement; setOpen(true); dismissHint(CMD_PALETTE_HINT_ID); }; const close = () => setOpen(false); useEffect(() => { if (!open) { restoreRef.current?.focus?.(); restoreRef.current = null; } }, [open]); useHotkey("mod+k", () => (open ? close() : openPalette()), { allowInInput: true }); const trapTab = (event: React.KeyboardEvent) => { if (event.key !== "Tab") return; const root = contentRef.current; if (!root) return; const focusables = Array.from(root.querySelectorAll<HTMLElement>('a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])')).filter((element) => element.offsetParent !== null); if (!focusables.length) { event.preventDefault(); return; } const [first] = focusables; const last = focusables.at(-1)!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-start bg-sage-1000/55 px-4 pt-[min(16vh,8rem)]" onClick={close} role="presentation"><div aria-label={t("label")} aria-modal="true" className="w-full max-w-xl overflow-hidden rounded-panel border border-riwaq-border-strong bg-riwaq-surface shadow-none" onClick={(event) => event.stopPropagation()} onKeyDown={(event) => { if (event.key === "Escape") { event.stopPropagation(); close(); return; } trapTab(event); }} ref={contentRef} role="dialog"><Command label={t("label")} loop><div className="border-b border-riwaq-border"><Command.Input autoFocus className="h-14 w-full bg-transparent px-5 text-sm text-riwaq-text outline-none placeholder:text-riwaq-muted" placeholder={t("search")} /></div><Command.List className="max-h-[min(55vh,30rem)] overflow-y-auto p-2"><Command.Empty className="px-3 py-8 text-center text-sm text-riwaq-muted">{t("empty")}</Command.Empty>{groups.map((group) => <Command.Group className="mb-2 last:mb-0" heading={group.heading} key={group.id}>{group.commands.map((command) => <Command.Item className="flex min-h-11 cursor-pointer items-center justify-between gap-4 rounded-control px-3 text-sm font-semibold text-riwaq-lilac aria-selected:bg-riwaq-elevated aria-selected:text-riwaq-text" key={command.id} onSelect={() => { command.run(); close(); }} value={command.label}><span>{command.label}</span>{command.hint ? <kbd className="rounded border border-riwaq-border bg-riwaq-bg px-1.5 py-0.5 font-mono text-xs text-riwaq-muted">{command.hint}</kbd> : null}</Command.Item>)}</Command.Group>)}</Command.List></Command></div></div>; }
