"use client";

import NextLink from "next/link";
import { useTranslations } from "next-intl";
import { ArrowRight, Fire, HeadphonesRound, Target } from "@solar-icons/react";
import { Button, Logo } from "@/components/ui";
import { Routes } from "@/constants";

const FEATURES = [{ icon: Target, title: "features.0.title", body: "features.0.body" }, { icon: HeadphonesRound, title: "features.1.title", body: "features.1.body" }, { icon: Fire, title: "features.2.title", body: "features.2.body" }] as const;
export function Landing() { const t = useTranslations("landing"); return <main className="min-h-dvh bg-base-200 text-sage-1000"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Logo href={Routes.Landing} size="7" /><nav className="flex items-center gap-2"><NextLink className="btn min-h-10 rounded-control border-transparent bg-transparent px-3 text-sm text-sage-800 hover:bg-sage-100" href={Routes.Login}>{t("nav.signIn")}</NextLink><NextLink className="btn btn-primary min-h-10 rounded-control px-4 text-sm" href={Routes.Login}>{t("nav.getStarted")}</NextLink></nav></header><section className="mx-auto grid max-w-4xl place-items-center px-6 pb-20 pt-20 text-center sm:pb-28 sm:pt-28"><p className="text-xs font-semibold uppercase tracking-normal text-sage-700">{t("hero.eyebrow")}</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-normal text-sage-1000 sm:text-6xl">{t("hero.headline")}</h1><p className="mt-6 max-w-xl text-base leading-7 text-sage-700 sm:text-lg">{t("hero.subcopy")}</p><Button className="mt-9" onClick={() => { window.location.assign(Routes.Login); }} size="lg"><span>{t("hero.cta")}</span><ArrowRight className="size-5" /></Button></section><section className="mx-auto grid max-w-6xl gap-4 px-6 pb-20 md:grid-cols-3">{FEATURES.map(({ icon: Glyph, title, body }) => <article className="rounded-panel border border-sage-300 bg-base-100 p-6" key={title}><span className="grid size-10 place-items-center rounded-control bg-sage-100 text-sage-800"><Glyph className="size-5" /></span><h2 className="mt-5 text-lg font-semibold tracking-normal text-sage-1000">{t(title)}</h2><p className="mt-2 text-sm leading-6 text-sage-700">{t(body)}</p></article>)}</section><p className="px-6 pb-10 text-center text-sm text-sage-600">{t("quote.text")} {t("quote.attribution")}</p></main>; }
