import { defineSlotRecipe } from "@chakra-ui/react";

export const menuSlotRecipe = defineSlotRecipe({
  slots: ["content", "item", "itemText", "itemGroup", "itemGroupLabel", "separator", "indicator"],
  base: {
    content: {
      bg: "bg.emphasized",
      color: "fg",
      boxShadow: "none",
      minW: "11.25rem",
      borderRadius: "xl",
      padding: "1.5",
      display: "flex",
      flexDirection: "column",
      gap: "0.5",
      zIndex: "overlay",
      transformOrigin: "var(--transform-origin)",
      _open: { animationName: "panel-in", animationDuration: "enter", animationTimingFunction: "enter" },
      _closed: { animationName: "panel-out", animationDuration: "exit", animationTimingFunction: "exit" },
      _motionReduce: { _open: { animationName: "fade-in" }, _closed: { animationName: "fade-out" } },
    },
    item: {
      display: "flex",
      alignItems: "center",
      gap: "2.5",
      paddingInline: "2.5",
      paddingBlock: "2",
      borderRadius: "md",
      fontSize: "sm",
      lineHeight: "1.2",
      cursor: "pointer",
      userSelect: "none",
      outline: "none",
      color: "fg",
      transitionProperty: "background-color, color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      "& svg": { boxSize: "4" },
      _hover: { bg: "whiteA.faint" },
      _highlighted: { bg: "whiteA.faint" },
      _active: { bg: "whiteA.dim" },
      "&[data-checked]": {
        bg: "primary.solid",
        color: "primary.contrast",
        _hover: { bg: "primary.emphasized", color: "primary.contrast" },
        _highlighted: { bg: "primary.emphasized", color: "primary.contrast" },
      },
      "&[data-danger]": {
        "& svg": { color: "fg.error" },
        _hover: { bg: "fg.error", color: "fg.inverted", "& svg": { color: "fg.inverted" } },
        _highlighted: { bg: "fg.error", color: "fg.inverted", "& svg": { color: "fg.inverted" } },
      },
      _disabled: { opacity: 0.5, cursor: "not-allowed", _hover: { bg: "transparent" } },
    },
    itemText: { flex: "1" },
    itemGroupLabel: {
      paddingInline: "2.5",
      paddingBlock: "1.5",
      textStyle: "label-md",
      color: "fg.subtle",
    },
    separator: {
      height: "1px",
      marginBlock: "1",
      borderWidth: "0",
      bg: "border",
    },
    indicator: { color: "fg.muted" },
  },
});
