import { defineSlotRecipe } from "@chakra-ui/react";

export const menuSlotRecipe = defineSlotRecipe({
  className: "khulwa-menu",
  slots: ["content", "item", "itemText", "itemGroup", "itemGroupLabel", "separator", "indicator"],
  base: {
    content: {
      bg: "glass.panelBg",
      borderWidth: "1px",
      borderColor: "glass.border",
      borderRadius: "surface",
      backdropFilter: "blur(28px) saturate(1.4)",
      boxShadow: "lg",
      padding: "1.5",
      minW: "11rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.5",
      zIndex: "overlay",
      transformOrigin: "var(--transform-origin)",
      _open: { animationName: "panel-in", animationDuration: "enter", animationTimingFunction: "enter" },
      _closed: { animationName: "panel-out", animationDuration: "exit", animationTimingFunction: "exit" },
    },
    item: {
      display: "flex",
      alignItems: "center",
      gap: "2.5",
      paddingInline: "2.5",
      paddingBlock: "2",
      borderRadius: "control",
      fontSize: "sm",
      lineHeight: "1.2",
      color: "fg.default",
      cursor: "pointer",
      userSelect: "none",
      outline: "none",
      transitionProperty: "background-color, color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      _hover: { bg: "bg.muted", color: "fg.default" },
      _highlighted: { bg: "bg.muted", color: "fg.default" },
      _active: { bg: "bg.emphasized" },
      _disabled: { opacity: 0.5, cursor: "not-allowed", _hover: { bg: "transparent" } },
    },
    itemText: { flex: "1" },
    itemGroupLabel: {
      paddingInline: "2.5",
      paddingBlock: "1.5",
      textStyle: "label-md",
      color: "fg.subtle",
    },
    separator: {
      height: "1px",
      bg: "border.subtle",
      marginBlock: "1",
    },
    indicator: { color: "fg.muted" },
  },
});
