import {
  createSlotRecipeContext,
  defineSlotRecipe,
  Input,
  Text,
  type HTMLChakraProps,
  type InputProps,
  type TextProps,
} from "@chakra-ui/react";
import { InlineEdit, type InlineEditProps } from "@/components/ui/inline-edit";

export const taskListSlotRecipe = defineSlotRecipe({
  slots: [
    "list",
    "item",
    "row",
    "meta",
    "actions",
    "stepRow",
    "steps",
    "editable",
    "action",
    "counter",
    "eta",
    "etaValue",
    "etaUnit",
    "addAction",
    "addStep",
    "addStepRow",
    "sectionTrigger",
    "sectionContent",
    "empty",
  ],
  base: {
    list: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0.5",
    },

    item: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0",
      animationName: "row-in",
      animationDuration: "enter",
      animationTimingFunction: "enter",
      animationFillMode: "backwards",
      _motionReduce: { animationName: "none" },
      "&[data-active]::before": {
        content: '""',
        position: "absolute",
        insetInlineStart: "0",
        insetBlockStart: "2.5",
        width: "3px",
        height: "4.5",
        rounded: "full",
        bg: "primary.solid",
      },
    },
    row: {
      display: "flex",
      alignItems: "center",
      gap: "2.5",
      paddingInlineStart: "2",
      paddingInlineEnd: "1.5",
      paddingBlock: "2",
      rounded: "md",
      transitionProperty: "background-color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      _hover: { bg: "whiteA.faint" },
    },

    meta: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      flexShrink: "0",
      textStyle: "xs",
      color: "fg.subtle",
      fontVariantNumeric: "tabular-nums",
    },

    actions: {
      display: "flex",
      alignItems: "center",
      gap: "0.5",
      flexShrink: "0",
    },
    stepRow: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      paddingInline: "2",
      rounded: "md",
      _hover: { bg: "whiteA.faint" },
    },
    steps: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "1",
      paddingInlineStart: "9",
      paddingBlock: "1.5",
    },
    editable: {
      flex: "1",
      minW: "0",
      textStyle: "sm",
      whiteSpace: "nowrap",
      overflowX: "auto",
      scrollbarWidth: "none",
      "&::-webkit-scrollbar": { display: "none" },
      color: "fg",
      cursor: "text",
      outline: "none",
      _focus: { boxShadow: "none" },
      "&[data-tone=muted]": { color: "fg.muted" },
      "&[data-completed]": { color: "fg.subtle", textDecoration: "line-through" },
      "&[data-completed]:focus": { textDecoration: "none", color: "fg" },
    },

    action: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: "0",
      boxSize: "6",
      rounded: "xs",
      border: "0",
      bg: "transparent",
      color: "fg.subtle",
      cursor: "pointer",
      transitionProperty: "background-color, color, transform",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      _hover: { color: "fg" },
      _active: { transform: "scale(0.94)", transitionDuration: "instant" },
      _motionReduce: { _active: { transform: "none" } },
      _disabled: { opacity: 0.5, cursor: "not-allowed" },
      "& svg": {
        transitionProperty: "transform",
        transitionDuration: "enter",
        transitionTimingFunction: "enter",
      },
      "&[aria-expanded=true] svg": { transform: "rotate(90deg)" },
      "&[data-danger]": { _hover: { color: "red.emphasized" } },
      "&[aria-pressed=true]": {
        color: "primary.solid",
        _hover: { color: "primary.emphasized" },
      },
      "&[data-overflow]": {
        position: "relative",
        boxSize: "6",
        "& svg": { boxSize: "4" },
        "&::after": {
          content: '""',
          position: "absolute",
          top: "50%",
          insetInlineStart: "50%",
          transform: "translate(-50%, -50%)",
          boxSize: "11",
        },
      },
    },

    counter: {
      flexShrink: "0",
      appearance: "none",
      border: "0",
      bg: "transparent",
      padding: "0",
      fontFamily: "inherit",
      textStyle: "xs",
      color: "fg.subtle",
      fontVariantNumeric: "tabular-nums",
      transitionProperty: "color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      "&[data-toggle]": {
        // peach.400/300 sit off the semantic scale: on-mesh foregrounds must brighten on hover
        color: "peach.400",
        cursor: "pointer",
        _hover: { color: "peach.300" },
      },
    },
    eta: {
      display: "inline-flex",
      alignItems: "baseline",
      gap: "0.5",
      flexShrink: "0",
      whiteSpace: "nowrap",
      fontVariantNumeric: "tabular-nums",
      cursor: "text",
    },
    etaValue: {
      display: "inline",
      textStyle: "xs",
      color: "inherit",
      cursor: "text",
      outline: "none",
      _focus: { boxShadow: "none" },
      "&[data-tone=muted]": { color: "fg.muted" },
    },
    etaUnit: {
      textStyle: "xs",
      color: "fg.muted",
    },
    addAction: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: "0",
      boxSize: "8",
      rounded: "full",
      border: "0",
      bg: "transparent",
      color: "primary.solid",
      cursor: "pointer",
      transitionProperty: "background-color, color, transform",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      "& svg": { boxSize: "5" },
      // peach.300 off the semantic scale: on-mesh foreground must brighten on hover
      _hover: { color: "peach.300" },
      _active: { transform: "scale(0.97)", transitionDuration: "instant" },
      _motionReduce: { _active: { transform: "none" } },
      _disabled: { opacity: 0.5, cursor: "not-allowed" },
    },
    addStep: {
      flex: "1",
      marginInlineStart: "1",
      color: "fg.muted",
      _placeholder: { color: "fg.subtle" },
      _focusVisible: { boxShadow: "focusRing" },
    },
    addStepRow: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      paddingTop: "0.5",
    },
    sectionTrigger: {
      display: "flex",
      alignItems: "center",
      gap: "1",
      w: "full",
      marginTop: "2",
      paddingInline: "2",
      paddingBlock: "1",
      cursor: "pointer",
      color: "fg.muted",
      textStyle: "label-md",
      "& svg": {
        transitionProperty: "transform",
        transitionDuration: "enter",
        transitionTimingFunction: "enter",
      },
      "&[data-state=open] svg": { transform: "rotate(90deg)" },
    },
    sectionContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0.5",
      paddingTop: "1",
    },
    empty: {
      textStyle: "sm",
      color: "fg.muted",
      textAlign: "center",
      paddingBlock: "8",
    },
  },
});

const ctx = createSlotRecipeContext({ key: "taskList" });

type DivProps = HTMLChakraProps<"div">;
type ButtonProps = HTMLChakraProps<"button">;

export const TaskList = {
  Root: ctx.withProvider<HTMLDivElement, DivProps>("div", "list"),
  Item: ctx.withContext<HTMLDivElement, DivProps>("div", "item"),
  Row: ctx.withContext<HTMLDivElement, DivProps>("div", "row"),

  Meta: ctx.withContext<HTMLDivElement, DivProps>("div", "meta"),

  Actions: ctx.withContext<HTMLDivElement, DivProps>("div", "actions"),
  Steps: ctx.withContext<HTMLDivElement, DivProps>("div", "steps"),
  StepRow: ctx.withContext<HTMLDivElement, DivProps>("div", "stepRow"),
  AddStepRow: ctx.withContext<HTMLDivElement, DivProps>("div", "addStepRow"),

  Action: ctx.withContext<HTMLButtonElement, ButtonProps>("button", "action", {
    defaultProps: { type: "button" },
  }),
  AddAction: ctx.withProvider<HTMLButtonElement, ButtonProps>("button", "addAction", {
    defaultProps: { type: "button" },
  }),

  Editable: ctx.withContext<HTMLParagraphElement, InlineEditProps>(InlineEdit, "editable"),
  Eta: ctx.withContext<HTMLParagraphElement, TextProps>(Text, "eta"),
  EtaValue: ctx.withContext<HTMLSpanElement, InlineEditProps>(InlineEdit, "etaValue", {
    defaultProps: { as: "span" },
  }),
  EtaUnit: ctx.withContext<HTMLSpanElement, TextProps>(Text, "etaUnit", {
    defaultProps: { as: "span" },
  }),
  Counter: ctx.withContext<HTMLButtonElement, ButtonProps>("button", "counter", {
    defaultProps: { type: "button" },
  }),
  AddStepInput: ctx.withContext<HTMLInputElement, InputProps>(Input, "addStep", {
    defaultProps: { variant: "plain", size: "sm" },
  }),
  SectionTrigger: ctx.withContext<HTMLButtonElement, ButtonProps>("button", "sectionTrigger"),
  SectionContent: ctx.withContext<HTMLDivElement, DivProps>("div", "sectionContent"),
  Empty: ctx.withContext<HTMLParagraphElement, TextProps>(Text, "empty"),
};
