import { defineSlotRecipe } from "@chakra-ui/react";

export const taskListSlotRecipe = defineSlotRecipe({
  slots: [
    "list",
    "item",
    "row",
    "meta",
    "actions",
    "stepRow",
    "steps",
    "editable",
    "action",
    "counter",
    "eta",
    "etaValue",
    "etaUnit",
    "addStep",
    "addStepRow",
    "sectionTrigger",
    "sectionContent",
    "empty",
  ],
  base: {
    list: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0.5",
    },

    item: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0",
      animationName: "row-in",
      animationDuration: "enter",
      animationTimingFunction: "enter",
      animationFillMode: "backwards",
      _motionReduce: { animationName: "none" },
      "&[data-active]::before": {
        content: '""',
        position: "absolute",
        insetInlineStart: "0",
        insetBlockStart: "2.5",
        width: "3px",
        height: "4.5",
        rounded: "full",
        bg: "primary.solid",
      },
    },
    row: {
      display: "flex",
      alignItems: "center",
      gap: "2.5",
      paddingInlineStart: "2",
      paddingInlineEnd: "1.5",
      paddingBlock: "2",
      rounded: "md",
      transitionProperty: "background-color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      _hover: { bg: "glass.subtle" },
    },

    meta: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      flexShrink: "0",
      textStyle: "xs",
      color: "fg.onMesh.subtle",
      fontVariantNumeric: "tabular-nums",
    },

    actions: {
      display: "flex",
      alignItems: "center",
      gap: "0.5",
      flexShrink: "0",
    },
    stepRow: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      paddingInline: "2",
      rounded: "md",
      _hover: { bg: "glass.subtle" },
    },
    steps: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "1",
      paddingInlineStart: "9",
      paddingBlock: "1.5",
    },
    editable: {
      flex: "1",
      minW: "0",
      textStyle: "sm",
      whiteSpace: "nowrap",
      overflowX: "auto",
      scrollbarWidth: "none",
      "&::-webkit-scrollbar": { display: "none" },
      color: "fg.onMesh",
      cursor: "text",
      outline: "none",
      "&[data-tone=muted]": { color: "fg.onMesh.muted" },
      "&[data-completed]": { color: "fg.onMesh.subtle", textDecoration: "line-through" },
      "&[data-completed]:focus": { textDecoration: "none", color: "fg.onMesh" },
    },

    action: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: "0",
      boxSize: "6",
      rounded: "xs",
      border: "0",
      bg: "transparent",
      color: "fg.onMesh.subtle",
      cursor: "pointer",
      transitionProperty: "background-color, color, transform",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      _hover: { bg: "glass.muted", color: "fg.onMesh" },
      _active: { transform: "scale(0.94)", transitionDuration: "instant" },
      _motionReduce: { _active: { transform: "none" } },
      _disabled: { opacity: 0.5, cursor: "not-allowed" },
      "& svg": {
        transitionProperty: "transform",
        transitionDuration: "enter",
        transitionTimingFunction: "enter",
      },
      "&[aria-expanded=true] svg": { transform: "rotate(90deg)" },
      "&[data-danger]": { _hover: { color: "red.emphasized" } },
      "&[aria-pressed=true]": {
        color: "primary.solid",
        _hover: { color: "primary.emphasized" },
      },
      "&[data-overflow]": {
        position: "relative",
        boxSize: "6",
        "&::after": {
          content: '""',
          position: "absolute",
          top: "50%",
          insetInlineStart: "50%",
          transform: "translate(-50%, -50%)",
          boxSize: "11",
        },
      },
    },

    counter: {
      flexShrink: "0",
      appearance: "none",
      border: "0",
      bg: "transparent",
      padding: "0",
      fontFamily: "inherit",
      textStyle: "xs",
      color: "fg.onMesh.subtle",
      fontVariantNumeric: "tabular-nums",
      transitionProperty: "color",
      transitionDuration: "enter",
      transitionTimingFunction: "enter",
      "&[data-toggle]": {
        // teal.400 sits off the native slot scale; documented exception until the P2 Field rework
        color: "teal.400",
        cursor: "pointer",
        _hover: { color: "teal.emphasized" },
      },
    },
    eta: {
      display: "inline-flex",
      alignItems: "baseline",
      gap: "0.5",
      flexShrink: "0",
      whiteSpace: "nowrap",
      fontVariantNumeric: "tabular-nums",
      cursor: "text",
    },
    etaValue: {
      display: "inline",
      textStyle: "xs",
      color: "inherit",
      cursor: "text",
      outline: "none",
      "&[data-tone=muted]": { color: "fg.onMesh.muted" },
    },
    etaUnit: {
      textStyle: "xs",
      color: "fg.onMesh.muted",
    },
    addStep: {
      flex: "1",
      marginInlineStart: "1",
      color: "fg.onMesh.muted",
      _placeholder: { color: "fg.onMesh.subtle" },
      _focusVisible: { boxShadow: "focusRing.glass" },
    },
    addStepRow: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      paddingTop: "0.5",
    },
    sectionTrigger: {
      display: "flex",
      alignItems: "center",
      gap: "1",
      w: "full",
      marginTop: "2",
      paddingInline: "2",
      paddingBlock: "1",
      cursor: "pointer",
      color: "fg.onMesh.muted",
      textStyle: "label-md",
      "& svg": {
        transitionProperty: "transform",
        transitionDuration: "enter",
        transitionTimingFunction: "enter",
      },
      "&[data-state=open] svg": { transform: "rotate(90deg)" },
    },
    sectionContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      gap: "0.5",
      paddingTop: "1",
    },
    empty: {
      textStyle: "sm",
      color: "fg.onMesh.muted",
      textAlign: "center",
      paddingBlock: "8",
    },
  },
});
